### ISSUE TITLE
Missing feature (or I'm stupid and can't find it)

### ISSUE THREAD

**Issue by Lokpique** [coenvdwel/rewatch#16]
Not sure if this is an issue or a suggestion.
I used to use this addon with only the tanks, utilizing the "add player" function to only show a plate for people I selected instead of the whole group.
Is this function here, and I'm missing it, or can this be added to the list of future features?
Without it I am unable to use the addon in it's current state.

**Comment by coenvdwel** [comment]
Sorry, not sure if this is still accurate!
