### ISSUE TITLE
WoW Classic - WotLK Support

### ISSUE THREAD

**Issue by DC4JG** [coenvdwel/rewatch#19]
Any chance of getting a Classic/WotLK version or some rough guidelines how to adapt it?

Retail version apparently fails because `GetSpecialization` changed, original WotLK version fails because it tries to register some probably no longer existing event.

Maybe helpful resources:
- https://wowpedia.fandom.com/wiki/Porting_addons_to_Classic
- https://github.com/tstirrat/LibClassicSpecs

I absolutely loved this addon as druid back in the days and would prefer it over e.g. Healbot or Vohdo raid frames.

**Comment by coenvdwel** [comment]
I wonder how their API works, with their classic-version-but-with-some-changes! I can't imagine their developers supporting running the old API from back then, but then again, I can't imagine them backporting...

All versions of Rewatch are still available on Curseforge, maybe those still work?
