### ISSUE TITLE
bad argument 

### ISSUE THREAD

**Issue by Baschtl77** [coenvdwel/rewatch#21]
Here an exception caught via bugsack.
I cannot tell how, but that LUA error occured:

9x bad argument #2 to '?' (Usage: self:SetStatusBarColor(color [, a]))
[string "=[C]"]: in function `SetStatusBarColor'
[string "@Rewatch/src/RewatchPlayer.lua"]:255: in function `SetPower'
[string "@Rewatch/src/RewatchPlayer.lua"]:356: in function `OnEvent'
[string "@Rewatch/src/RewatchPlayer.lua"]:204: in function <Rewatch/src/RewatchPlayer.lua:204>

Locals:
(*temporary) = "bad argument #2 to '?' (Usage: self:SetStatusBarColor(color [, a]))"

**Comment by coenvdwel** [comment]
Nice @Baschtl77, thank you! Actually managed to replicate this myself a little earlier, and already had a patch local - just pushed it to master! (4df23d4ae6d8e3ae68a87fdb673373502b7ed772)
